name: publish

on:
  release:
    types: [published]

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v2
        with:
          images: btravers/pdf-snapshot

      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.12.2
          run_install: true

      - run: cp ./README.md ./packages/jest/

      - run: cd ./packages/jest/ && pnpm version --no-git-tag-version ${{ github.event.release.tag_name }} && cd ../../

      - run: pnpm --filter ./packages/jest publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}